[package]
name = "rust_learning"
version = "0.1.0"
edition = "2024"

[dependencies]
windows = { version = "0.61.1", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System",
    "Win32_System_LibraryLoader",
    "Win32_Graphics_Gdi",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Dxgi_Common",
    "Win32_System_Com",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Direct3D_Fxc"] }
widestring = "1.0"
directx_math = "0.2.3"
windows-core = "0.61.2"
once_cell = "1.21.3"

